vars:
  SPOTIFY_PUBLIC: ""
  SPOTIFY_SECRET: ""
  TIMEZONE: "Europe/Berlin"
  LOG_LEVEL: "info"

sensitiveVars:
  secretName: "spotistats-secrets"

api:
  image:
    repository: docker.io
    image: yooooomi/your_spotify_server
    tag: "1.13.1"
    pullPolicy: IfNotPresent
  ingress:
    host: ""
    className: "nginx"
    annotations: {}
    tls:
      enabled: true
      secretName: "spotistats-api-tls"
      issuer: "letsencrypt-staging"
  resources: {}

web:
  image:
    repository: docker.io
    image: yooooomi/your_spotify_client
    tag: "1.13.1"
    pullPolicy: IfNotPresent
  ingress:
    host: ""
    className: "nginx"
    annotations: {}
    tls:
      enabled: true
      secretName: "spotistats-tls"
      issuer: "letsencrypt-staging"
  resources: {}

db:
  image:
    repository: docker.io
    image: mongo
    tag: "6.0.23"
    pullPolicy: IfNotPresent
  resources: {}
