vars:
  SPOTIFY_PUBLIC: ""
  SPOTIFY_SECRET: ""
  TIMEZONE: "Europe/Berlin"
  LOG_LEVEL: "info"

api:
  ingress:
    host: ""
    className: "nginx"
    annotations: {}
    tls:
      enabled: true
      secretName: "spotistats-api-tls"
      issuer: "letsencrypt-staging"
  resources:
    requests:
      memory: "150Mi"
      cpu: "50m"
    limits:
      memory: "250Mi"
      cpu: "100m"

web:
  ingress:
    host: ""
    className: "nginx"
    annotations: {}
    tls:
      enabled: true
      secretName: "spotistats-tls"
      issuer: "letsencrypt-staging"
  resources:
    requests:
      memory: "30Mi"
      cpu: "10m"
    limits:
      memory: "100Mi"
      cpu: "50m"

db:
  resources:
    requests:
      memory: "150Mi"
      cpu: "10m"
    limits:
      memory: "300Mi"
      cpu: "30m"
