apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spotistats.fullname" . }}-api
  labels:
    {{- include "spotistats.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      {{- include "spotistats.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: api
        {{- include "spotistats.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: api
          image: yooooomi/your_spotify_server:1.12.0
          resources:
            requests:
              memory: "150Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "100m"
          env:
            - name: LOG_LEVEL
              value: {{ .Values.vars.LOG_LEVEL }}
            - name: CLIENT_ENDPOINT
              value: {{ if .Values.web.ingress.tls.enabled }}https://{{ else }}http://{{ end }}{{ .Values.web.ingress.host }}
            - name: API_ENDPOINT
              value: {{ if .Values.api.ingress.tls.enabled }}https://{{ else }}http://{{ end }}{{ .Values.api.ingress.host }}
            - name: SPOTIFY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: {{ include "spotistats.fullname" . }}
                  key: SPOTIFY_PUBLIC
            - name: SPOTIFY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "spotistats.fullname" . }}
                  key: SPOTIFY_SECRET
            - name: MONGO_ENDPOINT
              value: "mongodb://{{ include "spotistats.fullname" . }}-mongo.{{ .Release.Namespace }}.svc.cluster.local:27017/your_spotify"
            - name: CORS
              {{- if .Values.api.ingress.tls.enabled }}
              value: "https://{{.Values.api.ingress.host}},https://{{.Values.web.ingress.host}}"
              {{- else }}
              value: "http://{{.Values.api.ingress.host}},http://{{.Values.web.ingress.host}}"
              {{- end }}
