apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotistats.fullname" . }}-api
  labels:
    {{- include "spotistats.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: api
    {{- include "spotistats.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
