apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotistats.fullname" . }}-mongo
  labels:
    {{- include "spotistats.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: mongo
    {{- include "spotistats.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
