apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spotistats.fullname" . }}-pvc
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
