apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spotistats.fullname" . }}-mongo
  labels:
    {{- include "spotistats.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: mongo
      {{- include "spotistats.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: mongo
        {{- include "spotistats.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: mongo
          image: {{ .Values.db.image.repository }}/{{ .Values.db.image.image }}:{{ .Values.db.image.tag }}
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          {{- with .Values.db.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: {{ include "spotistats.fullname" . }}-storage
              mountPath: /data/db
      volumes:
        - name: {{ include "spotistats.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ include "spotistats.fullname" . }}-pvc
