apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spotistats.fullname" . }}
  labels:
    {{- include "spotistats.labels" . | nindent 4 }}
type: Opaque
data:
  SPOTIFY_PUBLIC: {{ .Values.vars.SPOTIFY_PUBLIC }}
  SPOTIFY_SECRET: {{ .Values.vars.SPOTIFY_SECRET }}
