apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotistats.fullname" . }}-web
  labels:
    {{- include "spotistats.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: web
    {{- include "spotistats.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
